server:
  port: 8082

spring:
  application:
    name: MovieService
  data:
    mongodb:
     #uri: mongodb+srv://${db_username}:${db_password}@${db_url}
     #database: ${db_name}
     uri: mongodb+srv://${SECRET_DB_USERNAME}:${SECRET_DB_PASSWORD}@${SECRET_DB_URL}
     database: ${SECRET_DB_NAME}

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://172.17.0.2:8761/eureka

