apiVersion: v1
kind: Pod
metadata:
 labels: 
   name: "movieservice"
 name: "movieservice"
spec:
 containers:
  - name: movieservice
    image: bhargodevarya/movieservice:3
    # envFrom:
    #   - secretRef:
    #       name: movieservice-secrets
    env:
      - name: SECRET_DB_NAME
        valueFrom: 
          secretKeyRef:
            name: movieservice-secrets
            key: db_name
      - name: SECRET_DB_URL
        valueFrom: 
          secretKeyRef:
            name: movieservice-secrets
            key: db_url
      - name: SECRET_DB_PASSWORD
        valueFrom: 
          secretKeyRef:
            name: movieservice-secrets
            key: db_password
      - name: SECRET_DB_USERNAME
        valueFrom: 
          secretKeyRef:
            name: movieservice-secrets
            key: db_username
      # - name: db_username
      #   value: MovieUser
      # - name: db_password 
      #   value: ddBwXTcYMQmp42Dp
      # - name: db_url
      #   value: cloudplaygroundcluster.lxuiq.mongodb.net
      # - name: db_name
      #   value: MovieDB

  
